name: build-test
on: [push]
jobs:
  run-anchor-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: mrgnlabs/anchor-test-action@v0.4
        with:
          anchor-version: '0.30.1'
          solana-cli-version: '1.18.18'
          node-version: '22.2.0'
      - name: Install yarn dependencies
        run: yarn install
      - name: Build
        run: anchor build
      - name: Run tests
        run: anchor test
