name: build-test
on: [push]

env:
  SOLANA_VERSION: v1.9.9
  ANCHOR_VERSION: 0.24.2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/setup-anchor@v2
        with: 
          anchor-version: '0.30.1' 
          solana-cli-version: '1.18.17'
          node-version: '20.15.1'
      - run: anchor build
        shell: bash 
      - run: anchor test
        shell: bash
